spring:
   application:
      name: emaillist08
   profiles:
      active: development
   mvc:
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
   web:
      resources:
         static-locations: classpath:/assets/
   thymeleaf:
      prefix : classpath:templates/
      check-template-location: true
      mode: HTML
      suffix : .html
      cache : false

         

---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
   devtools:
      livereload:
         enabled: true
server:
   port: 8080
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
#
#Zuul Gateway
#eureka:
#   client:
#      fetchRegistry: true
#      registerWithEureka: false
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka
gateway:
   name: zuul
   endpoint: http://localhost:5555
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO


---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production             
server:
   port: 8883
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
#
#Zuul Gatwway
#eureka:
#   client:
#      fetchRegistry: true
#      registerWithEureka: false
#      serviceUrl:
#         defaultZone: http://49.247.9.194:8761/eureka
gateway:
   name: zuul
<<<<<<< HEAD
   endpoint: http://34.64.240.101:5555 
=======
   endpoint: http://localhost:5555 
>>>>>>> 1241fda5045b7c12f466aa6e4a4dac95902e3532
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      me:
         kickscar:
            emaillist:
               exception: ERROR
